version: '3.9'
services:
  java_app_create:
    container_name: java_app_create
    image: imagen-create:1.0.0-create
    build:
      context: ./springBoot-create
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgresdocker
    depends_on:
      - java_db
  java_app_delete:
    container_name: java_app_delete
    image: image-delete:1.0.0-delete
    build:
      context: ./springBoot-delete
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgresdocker
    depends_on:
      - java_db
  java_app_read:
    container_name: java_app_read
    image: image-read:1.0.0-read
    build:
      context: ./springBoot-read
    ports:
      - 8082:8082
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgresdocker
    depends_on:
      - java_db
  java_app_update:
    container_name: java_app_update
    image: image-update:1.0.0-update
    build:
      context: ./springBoot-update
    ports:
      - 8083:8083
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgresdocker
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:15.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresdocker
      - POSTGRES_DB=postgres
    volumes:
      - ./data_bd:/var/lib/postgresql/data