apiVersion: v1
kind: Pod
metadata:
  name: ejemplo-pod
spec:
  containers:
  - name: mi-contenedor
    image: nginx:latest
    volumeMounts:
    - name: almacenamiento-volumen
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: almacenamiento-volumen
    persistentVolumeClaim:
      claimName: ejemplo-pvc
