apiVersion: v1
kind: PersistentVolume
metadata:
  name: ejemplo-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: default
    name: ejemplo-pvc  # Nombre del PersistentVolumeClaim vinculado